version: "3.9"

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - cache
    networks:
      - app-network
    restart: on-failure

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: on-failure

  cache:
    image: redis
    env_file: .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: on-failure